package:
    name: dmimgtess
    version: 0.0.1

source:
    git_url: https://github.com/kglotfelty/dmimgtess.git

requirements:
    build:
      - ciao
      - dmimgio
      - readline_pc

    run:
      - ciao
      - cfitsio
      - readline
      - ncurses
      
about:
    home: http://hea-www.cfa.harvard.edu/~kjg/kciao
    license: Public
    summary: CIAO tool to compute Voronoi tesselation
