package:
    name: dmimgtess
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/dmimgtess.git
    git_tag: 4.13.0

requirements:
    build:
      - ciao=4.13
      - dmimgio
      - readline_pc

    run:
      - ciao=4.13
      - cfitsio
      - readline
      - ncurses
      
about:
    home: https://github.com/kglotfelty/dmimgtess/
    license: Public
    summary: CIAO tool to compute Voronoi tesselation
