package:
    name: pars2tab
    version: 4.18.0

source:
    git_url: https://github.com/kglotfelty/pars2tab.git
    git_branch: main

requirements:
    build:
      - ciao=4.18.0
      - pkg-config
      - libiconv
#      - readline_pc

#    run:
#      - ciao=4.18.0
#      - cfitsio
#      - readline
#      - ncurses

about:
    home: https://github.com/kglotfelty/pars2tab/
    license: Public
    summary: Convert a stack of parameter files to a table
