package:
    name: pars2tab
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/pars2tab.git
    git_tag: 4.13.0

requirements:
    build:
      - ciao=4.13
      - readline_pc

    run:
      - ciao=4.13
      - cfitsio
      - readline
      - ncurses
      
about:
    home: https://github.com/kglotfelty/pars2tab/
    license: Public
    summary: Convert a stack of parameter files to a table
