package:
    name: qocat
    version: 4.13.1

source:
    git_url: https://github.com/kglotfelty/ocat
    git_rev: 4.13.1

build:
    noarch: python

requirements:
    build:
      - ciao=4.13

    run:
      - ciao=4.13
      - ciao-contrib=4.13
      
about:
    home: https://github.com/kglotfelty/ocat/
    license: Public
    summary: Query Chandra observation catalog
