package:
    name: qocat
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/ocat

requirements:
    build:
      - ciao=4.13

    run:
      - ciao=4.13
      
about:
    home: https://github.com/kglotfelty/ocat/
    license: Public
    summary: Query Chandra observation catalog
