#!/bin/bash

#PATH=${PATH}:/data/lenin2/Test/CIAO4.12/Conda/miniconda/bin
PATH=${PATH}:/export/miniconda/bin

ciaover=ciao
ciaourl=https://cxc.cfa.harvard.edu/conda/
outdir=`pwd`/Out

#
# Libs
#


conda build \
  --output-folder ${outdir} \
  -c ${ciaourl}/${ciaover} \
  -c file://${outdir} \
  readline_pc

conda index $outdir

for l in dmimgio dmfilters
do
    conda build \
      --output-folder ${outdir} \
      -c ${ciaourl}/${ciaover} \
      -c file://${outdir} \
      $l
done

conda index $outdir

#
# Tools
#

for t in dmimggrad dmimgtess dmmaskstat dmradar dmscopy mktae pars2tab \
   resample_image dmnautilus 
do
    conda build \
      --output-folder ${outdir} \
      -c ${ciaourl}/${ciaover} \
      -c file://${outdir} \
      $t
done


conda index $outdir

for d in emodel cipt colorcolor qocat statmap adaptivebin temperaturemap
do 
  conda build --output-folder ${outdir} \
    -c ${ciaourl}/${ciaover} \
    -c file://${outdir} \
    $d
done

conda build --output-folder ${outdir} \
  -c file://${outdir} \
  -c ${ciaourl}/${ciaover} \
  zciao 


conda index $outdir


###conda remove -y -n ciao-4.12b1a pars2tab dmimgio resample_image
###
###conda install -y -n ciao-4.12b1a -c file://`pwd`/Out pars2tab dmimgio resample_image
###
###conda build purge
