#!/bin/bash

PATH=${PATH}:/data/lenin2/Test/CIAO4.12/Conda/miniconda/bin

ciaover=conda-ciao4.12b1a
ciaourl=ftp://cxc.cfa.harvard.edu/pub/ctest_dl/test
outdir=`pwd`/Out

#
# Libs
#
for l in dmimgio dmfilters
do
    conda build \
      --output-folder ${outdir} \
      -c ${ciaourl}/${ciaover} \
      -c file://${outdir} \
      $l
done

conda index Out

#
# Tools
#

for t in dmimggrad dmimgtess dmmaskstat dmradar dmscopy mktae pars2tab \
   resample_image dmnautilus 
do
    conda build \
      --output-folder ${outdir} \
      -c ${ciaourl}/${ciaover} \
      -c file://${outdir} \
      $t
done

conda build --output-folder `pwd`/Out -c file://`pwd`/Out   \
  -c ftp://cxc.cfa.harvard.edu/pub/ctest_dl/test/conda-ciao4.12b1a  zciao 


conda index Out



###conda remove -y -n ciao-4.12b1a pars2tab dmimgio resample_image
###
###conda install -y -n ciao-4.12b1a -c file://`pwd`/Out pars2tab dmimgio resample_image
###
###conda build purge
