package:
    name: dmimgio
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/dmimgio.git
    git_rev: 4.13.0

requirements:
    build:
      - ciao=4.13
      - readline_pc
      
about:
    home: https://github.com/kglotfelty/dmimgio/
    license: Public
    summary: I/O library to make handling 2D images easier
