package:
    name: dmfilters
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/dmfilters.git
    git_tag: 4.13.0

requirements:
    build:
      - ciao=4.13
      - readline_pc
      
about:
    home: https://github.com/kglotfelty/dmfilters/
    license: Public
    summary: 'A collection of statistics functions used for filtering'
