package:
    name: emodel
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/ellipse_model/
    git_rev: 4.13.0

build:
    noarch: python

requirements:
    build:
      - ciao=4.13

    run:
      - ciao=4.13
      - ciao-contrib=4.13
      
about:
    home: https://github.com/kglotfelty/ellipse_model/
    license: Public
    summary: Construct 2D model from table of enclosed ellipse fractions
