package:
    name: dmscopy
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/dmscopy.git
    git_rev: 4.13.0

requirements:
    build:
      - ciao=4.13
      - readline_pc

    run:
      - ciao=4.13
      - cfitsio
      - readline
      - ncurses
      
about:
    home: https://github.com/kglotfelty/dmscopy/
    license: Public
    summary: Make multiple copies of file in one pass.
