package:
    name: dmscopy
    version: 0.0.1

source:
    git_url: https://github.com/kglotfelty/dmscopy.git

requirements:
    build:
      - ciao

    run:
      - ciao
      - cfitsio
      - readline
      - ncurses
      
about:
    home: http://hea-www.cfa.harvard.edu/~kjg/kciao
    license: Public
    summary: Reproject an image to a new WCS by resampling integer pixel values
