package:
    name: dmmaskstat
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/dmmaskstat.git
    git_rev: 4.13.0

requirements:
    build:
      - ciao=4.13
      - dmimgio
      - dmfilters
      - readline_pc

    run:
      - ciao=4.13
      - cfitsio
      - readline
      - ncurses
      
about:
    home: https://github.com/kglotfelty/dmmaskstat/
    license: Public
    summary: CIAO tool to compute image statistics in mapped out regions

