package:
    name: adaptivebin
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/AdaptiveBin
    git_rev: 4.13.0

build:
    noarch: python

requirements:
    build:
      - ciao=4.13

    run:
      - ciao=4.13
      - ciao-contrib=4.13
      
about:
    home: https://github.com/kglotfelty/AdaptiveBin
    license: Public
    summary: A collection of adaptive binning tools
