package:
    name: cipt
    version: 0.0.1

source:
    git_url: https://github.com/kglotfelty/CIPT

requirements:
    build:
      - ciao

    run:
      - ciao
      
about:
    home: http://hea-www.cfa.harvard.edu/~kjg/kciao
    license: Public
    summary: CIAO Image Processing Toolkit
