package:
    name: cipt
    version: 4.13.1

source:
    git_url: https://github.com/kglotfelty/CIPT
    git_rev: 4.13.1

requirements:
    build:
      - ciao=4.13

    run:
      - ciao=4.13
      
about:
    home: http://hea-www.cfa.harvard.edu/~kjg/kciao
    license: Public
    summary: CIAO Image Processing Toolkit
