package:
    name: cipt
    version: 4.13.1

source:
    git_url: https://github.com/kglotfelty/CIPT
    git_rev: 4.13.1

build:
    noarch: python

requirements:
    build:
      - ciao=4.13

    run:
      - ciao=4.13
      - ciao-contrib=4.13
      
about:
    home: https://github.com/kglotfelty/CIPT
    license: Public
    summary: CIAO Image Processing Toolkit
