package:
    name: temperaturemap
    version: 4.13.1

source:
    git_url: https://github.com/kglotfelty/TemperatureMap
    git_rev: 4.13.1

requirements:
    build:
      - ciao=4.13

    run:
      - ciao=4.13
      
about:
    home: https://github.com/kglotfelty/TemperatureMap
    license: Public
    summary: A collection of scripts to compute temperature maps
