package:
    name: zciao
    version: 0.0.2
    
requirements:
    build:
        - dmimggrad
        - dmimgtess
        - dmmaskstat
        - dmradar
        - dmscopy
        - pars2tab
        - resample_image
        - cipt
        - colorcolor
        - qocat
        - statmap
        - adaptivebin
        - temperaturemap
        - emodel
        - mktae
        - dmnautilus

    run:
        - ciao
        - dmimggrad
        - dmimgtess
        - dmmaskstat
        - dmradar
        - dmscopy
        - pars2tab
        - resample_image
        - cipt
        - colorcolor
        - qocat
        - statmap
        - adaptivebin
        - temperaturemap
        - emodel
        - mktae
        - dmnautilus
        

about:
    home: https://hea-www.cfa.harvard.edu/~kjg/ciao
    license: Public
    summary: "My collection of extra CIAO tools and prototypes"


