package:
    name: zciao
    version: 4.13.4

build:
    number: 0
    always_include_files:
      - binexe/dmnautilus
      - bin/dmnautilus
      - param/dmnautilus.par
      - share/doc/xml/dmnautilus.xml

    
requirements:
    build:
        - dmimggrad=4.13.0
        - dmimgtess=4.13.0
        - dmmaskstat=4.13.0
        - dmradar=4.13.3
        - dmscopy=4.13.0
        - pars2tab=4.13.0
        - resample_image=4.13.0
        - cipt=4.13.1
        - colorcolor=4.13.0
        - qocat=4.13.1
        - statmap=4.13.0
        - adaptivebin=4.13.1
        - temperaturemap=4.13.1
        - emodel=4.13.0
        - mktae=4.13.0
        - dmnautilus=4.13.1
        - dmimgproject2=4.13.1

    run:
        - ciao=4.13
        - dmimggrad=4.13.0
        - dmimgtess=4.13.0
        - dmmaskstat=4.13.0
        - dmradar=4.13.3
        - dmscopy=4.13.0
        - pars2tab=4.13.0
        - resample_image=4.13.0
        - cipt=4.13.1
        - colorcolor=4.13.0
        - qocat=4.13.1
        - statmap=4.13.0
        - adaptivebin=4.13.1
        - temperaturemap=4.13.1
        - emodel=4.13.0
        - mktae=4.13.0
        - dmnautilus=4.13.1
        - dmimgproject2=4.13.1

about:
    home: https://hea-www.cfa.harvard.edu/~kjg/ciao
    license: Public
    summary: "My collection of extra CIAO tools and prototypes"


