package:
    name: zciao
    version: 4.13.1
    
requirements:
    build:
        - dmimggrad=4.13.0
        - dmimgtess=4.13.0
        - dmmaskstat=4.13.0
        - dmradar=4.13.0
        - dmscopy=4.13.0
        - pars2tab=4.13.0
        - resample_image=4.13.0
        - cipt=4.13.1
        - colorcolor=4.13.0
        - qocat=4.13.1
        - statmap=4.13.0
        - adaptivebin=4.13.0
        - temperaturemap=4.13.1
        - emodel=4.13.0
        - mktae=4.13.0
        - dmnautilus=4.13.0

    run:
        - ciao=4.13
        - dmimggrad=4.13.0
        - dmimgtess=4.13.0
        - dmmaskstat=4.13.0
        - dmradar=4.13.0
        - dmscopy=4.13.0
        - pars2tab=4.13.0
        - resample_image=4.13.0
        - cipt=4.13.1
        - colorcolor=4.13.0
        - qocat=4.13.1
        - statmap=4.13.0
        - adaptivebin=4.13.0
        - temperaturemap=4.13.1
        - emodel=4.13.0
        - mktae=4.13.0
        - dmnautilus=4.13.0
        

about:
    home: https://hea-www.cfa.harvard.edu/~kjg/ciao
    license: Public
    summary: "My collection of extra CIAO tools and prototypes"


