package:
    name: statmap
    version: 0.0.1

source:
    git_url: https://github.com/kglotfelty/statmap

requirements:
    build:
      - ciao

    run:
      - ciao
      
about:
    home: http://hea-www.cfa.harvard.edu/~kjg/kciao
    license: Public
    summary: Compute stats for map'ed regions.
