package:
    name: statmap
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/statmap
    git_rev: 4.13.0

build:
    noarch: python

requirements:
    build:
      - ciao=4.13

    run:
      - ciao=4.13
      - ciao-contrib=4.13
      
about:
    home: https://github.com/kglotfelty/statmap
    license: Public
    summary: Compute stats for map'ed regions.
