package:
    name: dmradar
    version: 0.0.1

source:
    git_url: https://github.com/kglotfelty/dmradar.git

requirements:
    build:
      - ciao
      - dmimgio

    run:
      - ciao
      - cfitsio
      - readline
      - ncurses
      
about:
    home: http://hea-www.cfa.harvard.edu/~kjg/kciao
    license: Public
    summary: Reproject an image to a new WCS by resampling integer pixel values
