package:
    name: dmradar
    version: 4.13.1

source:
    git_url: https://github.com/kglotfelty/dmradar.git
    git_rev: 4.13.1

requirements:
    build:
      - ciao=4.13
      - dmimgio
      - readline_pc

    run:
      - ciao=4.13
      - cfitsio
      - readline
      - ncurses
      
about:
    home: https://github.com/kglotfelty/dmradar/
    license: Public
    summary: Polar version of dmnautilus adaptive binning tool
