package:
    name: resample_image
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/resample_image.git
    git_rev: 4.13.0

requirements:
    build:
      - ciao=4.13
      - dmimgio
      - readline_pc

    run:
      - ciao=4.13
      - cfitsio
      - readline
      - ncurses
      
about:
    home: https://github.com/kglotfelty/resample_image/
    license: Public
    summary: Reproject an image to a new WCS by resampling integer pixel values
