package:
    name: colorcolor
    version: 4.13.0

source:
    git_url: https://github.com/kglotfelty/ColorColor

requirements:
    build:
      - ciao=4.13

    run:
      - ciao=4.13
      
about:
    home: https://github.com/kglotfelty/ColorColor
    license: Public
    summary: Create Color Color (hardness ratio) diagrams
