package:
    name: color_color
    version: 0.0.1

source:
    git_url: https://github.com/kglotfelty/ColorColor

requirements:
    build:
      - ciao

    run:
      - ciao
      
about:
    home: http://hea-www.cfa.harvard.edu/~kjg/kciao
    license: Public
    summary: Create Color Color (hardness ratio) diagrams
