package:
    name: dmnautilus
    version: 4.13.1

source:
    git_url: https://github.com/kglotfelty/dmnautilus.git
    git_rev: 4.13.1

requirements:
    build:
      - ciao=4.13
      - dmimgio
      - readline_pc

    run:
      - ciao=4.13
      - cfitsio
      - readline
      - ncurses

build:
    always_include_files:
      - binexe/dmnautilus
      - bin/dmnautilus
      - param/dmnautilus.par
      - share/doc/xml/dmnautilus.xml

about:
    home: https://github.com/kglotfelty/dmnautilus.git
    license: Public
    summary: Replacement for CIAOs dmnautilus tool with min threshold method.
