package:
    name: dmnautilus
    version: 0.0.1

source:
    git_url: https://github.com/kglotfelty/dmnautilus.git
    git_tag: master

requirements:
    build:
      - ciao
      - dmimgio

    run:
      - ciao
      - cfitsio
      - readline
      - ncurses

build:
    always_include_files:
      - binexe/dmnautilus
      - bin/dmnautilus
      - param/dmnautilus.par
      - share/doc/xml/dmnautilus.xml

about:
    home: http://hea-www.cfa.harvard.edu/~kjg/kciao
    license: Public
    summary: Reproject an image to a new WCS by resampling integer pixel values
